import { supabase } from "@/config/supabase";
import type { CreateInvoiceData, Invoice } from "@/types/invoices";
import type { Database, Json } from "@/types/supabase";

/**
 * Gets all invoices with business information
 *
 * @param businessId - Optional business ID to filter by
 * @param budgetReference - Optional budget reference to filter by
 * @returns Array of invoices with business details
 * @throws Error if fetch fails
 */
export const getAllInvoices = async (
  businessId?: string,
  budgetReference?: string,
): Promise<Invoice[]> => {
  let query = supabase.from("invoices").select(
    `
      *,
      business:business_id (
        id,
        name
      )
    `,
  );

  // Apply filters if provided
  if (businessId) {
    query = query.eq("business_id", businessId);
  }

  if (budgetReference) {
    query = query.eq("budget_reference", budgetReference);
  }

  const { data, error } = await query.order("created_at", { ascending: false });

  if (error) {
    console.error("Error fetching invoices:", error);
    throw new Error(
      error.message ||
        "No se pudieron cargar las facturas. Por favor, inténtelo de nuevo.",
    );
  }

  return (data || []) as Invoice[];
};

/**
 * Creates a new invoice in Supabase
 * Invoice number is auto-generated by the database trigger
 *
 * @param invoiceData - Data for the new invoice
 * @returns The created invoice
 * @throws Error if creation fails
 */
export const createInvoice = async (
  invoiceData: CreateInvoiceData,
): Promise<Invoice> => {
  const insertData: Database["public"]["Tables"]["invoices"]["Insert"] = {
    business_id: invoiceData.business_id,
    invoices_type_id: invoiceData.invoices_type_id,
    taxes_type_id: invoiceData.taxes_type_id,
    budget_reference: invoiceData.budget_reference,
    budgetlines: invoiceData.budgetlines as unknown as Json,
    price: invoiceData.price as unknown as Json,
  };

  const { data, error } = await supabase
    .from("invoices")
    .insert(insertData as never)
    .select()
    .single();

  if (error) {
    console.error("Error creating invoice:", error);
    throw new Error(
      error.message ||
        "No se pudo crear la factura. Por favor, inténtelo de nuevo.",
    );
  }

  if (!data) {
    throw new Error("No se recibió respuesta al crear la factura.");
  }

  return data as Invoice;
};
