import { type FC, useEffect, useMemo } from "react";
import { Controller, useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import Button from "@/components/shared/Button";
import InputField from "@/components/shared/InputField";
import SelectField from "@/components/shared/SelectField";
import type { Expense, ExpensePayload } from "@/types/expenses";
import type { ExpenseCategory } from "@/types/expensesCategories";

const expenseSchema = z.object({ proveedor: z.string().trim().min(1, "Obligatorio"), principal: z.string().min(1, "Selecciona una categoría"), secundario: z.string().min(1, "Selecciona una subcategoría"), baseImponible: z.number().finite().min(0, "Debe ser ≥ 0"), fecha: z.string().min(1, "Obligatorio") });
export type ExpenseFormValues = z.infer<typeof expenseSchema>;
interface Props { isOpen: boolean; expense: Expense | null; categories: ExpenseCategory[]; isSaving: boolean; error?: string; onClose: () => void; onSubmit: (payload: ExpensePayload) => void; }
const roundCents = (value: number) => Math.round((value + Number.EPSILON) * 100) / 100;

export const ExpenseFormModal: FC<Props> = ({ isOpen, expense, categories, isSaving, error, onClose, onSubmit }) => {
  const { control, handleSubmit, reset, watch, setValue, formState: { errors } } = useForm<ExpenseFormValues>({ resolver: zodResolver(expenseSchema), defaultValues: { proveedor: "", principal: "", secundario: "", baseImponible: 0, fecha: "" } });
  const principal = watch("principal"); const secundario = watch("secundario"); const base = watch("baseImponible");
  useEffect(() => { if (isOpen) reset({ proveedor: expense?.proveedor ?? "", principal: expense?.principal ?? "", secundario: expense?.secundario ?? "", baseImponible: expense?.baseImponible ?? 0, fecha: expense?.fecha.slice(0, 10) ?? "" }); }, [expense, isOpen, reset]);
  const principals = useMemo(() => [...new Set([...categories.map((item) => item.principal), ...(expense ? [expense.principal] : [])])].map((value) => ({ value, label: value })), [categories, expense]);
  const secondaries = useMemo(() => categories.filter((item) => item.principal === principal).map((item) => ({ value: item.subcategoria, label: item.subcategoria })), [categories, principal]);
  const selectedCategory = categories.find((item) => item.principal === principal && item.subcategoria === secundario);
  const tax = selectedCategory?.iva ?? (expense?.principal === principal && expense.secundario === secundario ? expense.impuesto : 0);
  if (!isOpen) return null;
  return <div className="fixed inset-0 z-50 flex items-center justify-center p-4"><div className="absolute inset-0 bg-black/50" onClick={isSaving ? undefined : onClose} aria-hidden="true" /><form onSubmit={handleSubmit((values) => onSubmit({ ...values, fecha: new Date(`${values.fecha}T00:00:00.000Z`).toISOString(), impuesto: tax, total: roundCents(values.baseImponible * (1 + tax / 100)) }))} noValidate className="relative w-full max-w-xl rounded-2xl bg-white p-6 shadow-2xl"><h2 className="text-xl font-semibold text-gray-900">{expense ? "Editar gasto" : "Nuevo gasto"}</h2><div className="mt-5 space-y-4"><Controller name="proveedor" control={control} render={({ field }) => <InputField label="Proveedor" name={field.name} value={field.value} onChange={field.onChange} onBlur={field.onBlur} required error={errors.proveedor?.message} />} /><div className="grid gap-4 sm:grid-cols-2"><Controller name="principal" control={control} render={({ field }) => <SelectField label="Principal" name={field.name} value={field.value} onChange={(event) => { field.onChange(event.target.value); setValue("secundario", ""); }} options={principals} placeholder="Selecciona principal" required error={errors.principal?.message} />} /><Controller name="secundario" control={control} render={({ field }) => <SelectField label="Secundario" name={field.name} value={field.value} onChange={field.onChange} options={secondaries} placeholder="Selecciona secundario" disabled={!principal} required error={errors.secundario?.message} />} /></div><div className="grid gap-4 sm:grid-cols-2"><Controller name="baseImponible" control={control} render={({ field }) => <InputField label="Base imponible (€)" name={field.name} type="number" value={field.value} onChange={(event) => field.onChange(event.target.value === "" ? Number.NaN : Number(event.target.value))} onBlur={field.onBlur} required error={errors.baseImponible?.message} />} /><InputField label="Impuesto (%)" name="impuesto" value={tax} onChange={() => {}} disabled /></div><div className="grid gap-4 sm:grid-cols-2"><InputField label="Total (€)" name="total" value={roundCents((Number.isFinite(base) ? base : 0) * (1 + tax / 100))} onChange={() => {}} disabled /><Controller name="fecha" control={control} render={({ field }) => <InputField label="Fecha" name={field.name} type="date" value={field.value} onChange={field.onChange} onBlur={field.onBlur} required error={errors.fecha?.message} />} /></div>{error && <p className="text-sm text-red-600">{error}</p>}</div><div className="mt-6 flex justify-end gap-3"><Button title="Cancelar" type="button" variant="secondary" onClick={onClose} disabled={isSaving} /><Button title={expense ? "Guardar cambios" : "Crear gasto"} type="submit" onClick={() => {}} loading={isSaving} /></div></form></div>;
};
